modLoader="javafml"
loaderVersion="[50,)" # Forge 50.x é o indicado para Minecraft 1.21.4
license="All Rights Reserved"

[[mods]]
modId="portalgun"
version="1.0.0"
displayName="Portal Gun"
authors="Slinky"
description='''Mod de portalgun que eu compliquei bem mais que o necessário'''

[[dependencies.portalgun]]
modId="forge"
mandatory=true
versionRange="[50,)"
ordering="NONE"
side="BOTH"

[[dependencies.portalgun]]
modId="minecraft"
mandatory=true
versionRange="[1.21.4,1.22)"
ordering="NONE"
side="BOTH"
